import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Navbar from '@/components/Navbar'
import Sidebar from './_components/Sidebar'
import NavbarCustomer from './_components/NavbarCustomer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className="h-screen w-screen flex">
       
        
        <Sidebar/>
<div className="flex flex-col  w-full">
 <NavbarCustomer/> 
        {children}
</div>

      
        
        </body>
    </html>
  )
}
